spring.application.name=readingvault
# Configuración de la Base de Datos
# spring.datasource.url=${SPRING_DATASOURCE_URL}
# spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
# spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# LOCAL LOCAL LOCAL LOCAL LOCAL LOCAL
spring.datasource.url=jdbc:mysql://localhost:3306/reading_vault?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=toor
# FRONTEND_URL=http://localhost:5173
# CLOUDINARY
# cloudinary.cloud_name=dng49vizq
# cloudinary.api_key=983843216921623
# cloudinary.api_secret=yAQAPPYd_uoEv-B8zjn1tT-BlqQ

# GOOGLE
# google.books.api.key=AIzaSyDDNlPeuOKajabvnfUj1nagkiMD8sYnGLA
#----------------------------------

# Configuración de JPA / Hibernate
# 'update' para crear las tablas automaticamente
spring.jpa.hibernate.ddl-auto=update

# Sentencias SQL por consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Muestra los valores reales (email, nombres, etc.) 
logging.level.org.hibernate.orm.jdbc.bind=trace

# Ver los valores reales que se envían (Email, Passwords, etc.)
logging.level.org.hibernate.type=trace

# Límite máximo para un solo archivo (ejemplo: 5 Megabytes)
spring.servlet.multipart.max-file-size=10MB

# Límite máximo para toda la petición (útil si subieras varios archivos a la vez)
spring.servlet.multipart.max-request-size=10MB

# Ver errores detallados de Spring Boot
# Esto te ayudará mucho con los errores de "UnsatisfiedDependency"
logging.level.org.springframework.boot.context.embedded=DEBUG
logging.level.org.springframework.boot.diagnostics=DEBUG

# Ver mensajes de error reales en las respuestas HTTP
spring.web.error.include-message=always
logging.level.com.readingvault=DEBUG


# CLOUDINARY
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}

#GOOGLE
google.books.api.key=${GOOGLE_BOOKS_API_KEY}

FRONTEND_URL=${FRONTEND_URL}
