spring.application.name=readingvault
# Configuración de la Base de Datos
spring.datasource.url=jdbc:mysql://localhost:3306/reading_vault?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=toor
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA / Hibernate
# 'update' para crear las tablas automaticamente
spring.jpa.hibernate.ddl-auto=update

# Sentencias SQL por consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Muestra los valores reales (email, nombres, etc.) 
logging.level.org.hibernate.orm.jdbc.bind=trace

# Ver los valores reales que se envían (Email, Passwords, etc.)
logging.level.org.hibernate.type=trace

# API de Google
google.books.api.key=AIzaSyDDNlPeuOKajabvnfUj1nagkiMD8sYnGLA

# Ver errores detallados de Spring Boot
# Esto te ayudará mucho con los errores de "UnsatisfiedDependency"
logging.level.org.springframework.boot.context.embedded=DEBUG
logging.level.org.springframework.boot.diagnostics=DEBUG

# Ver mensajes de error reales en las respuestas HTTP
spring.web.error.include-message=always
logging.level.com.readingvault=DEBUG